<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Refresh</name>
   <tag></tag>
   <elementGuidId>e994b56b-1f7a-4f71-8c41-3226cb681a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.mr-3.px-4.mb-2.mb-sm-0.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9c55d29-09cf-4ee5-8deb-4b9339e68f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bab7952f-1447-412d-827b-5a63d9e86776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-3 px-4 mb-2 mb-sm-0 btn-success</value>
      <webElementGuid>3454892c-2f7f-4132-bd69-f94982fdfa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Refresh
          </value>
      <webElementGuid>9ba18a04-303f-4e06-a867-8f9329f286d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;main-menuboard&quot;]/div[2]/div[@class=&quot;dashboard-section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row mt-2 mb-4&quot;]/div[@class=&quot;col&quot;]/span[@class=&quot;hide-on-650px&quot;]/button[@class=&quot;btn mr-3 px-4 mb-2 mb-sm-0 btn-success&quot;]</value>
      <webElementGuid>d8b1b649-6aaa-4bf2-b32d-f00b7a303119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>57f14bbf-6c7b-40c8-86f2-f65525dc87b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/div[2]/div/div/div/div[2]/span/button</value>
      <webElementGuid>9e59c8bf-feaa-4549-9248-3a9568760c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet List'])[3]/following::button[1]</value>
      <webElementGuid>bea49cdb-11da-4547-ad87-6a2c317d6136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet List'])[2]/following::button[1]</value>
      <webElementGuid>8e4b88c7-aa28-4bcc-8990-b2395fff7143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Filter'])[1]/preceding::button[1]</value>
      <webElementGuid>b3a6bec5-b99f-415a-adc0-6acc02ded4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Outlet'])[1]/preceding::button[2]</value>
      <webElementGuid>40d541ac-b17d-454e-8a6b-c7770666cc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh']/parent::*</value>
      <webElementGuid>f5744528-8854-4cb1-b4df-aa1f8e992a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>f7d9cacb-b3f0-46b9-a02b-d74dda3e179f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
            Refresh
          ' or . = '
            Refresh
          ')]</value>
      <webElementGuid>1b871a62-d783-43a7-8e2d-a14070904896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
