<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Master Data</name>
   <tag></tag>
   <elementGuidId>a98c889a-d6ad-43d5-be5a-e81a54f191d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div/ul[4]/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>26594d9f-0bee-47fb-a129-e45d73b3d4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-sub-menu collapsed</value>
      <webElementGuid>223c68bf-3f35-4f81-bb1f-275ce06a8d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse5</value>
      <webElementGuid>7a46dbef-c5c0-4f29-a1f4-3c72e8a3a56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f389364-ed48-4ac7-9493-fc297241a9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e14324ef-e23a-4def-b883-ee54d835d4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>faf8c922-543c-4751-b330-d6cc5098a7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;side-menu&quot;]/div[1]/ul[4]/li[@class=&quot;has-sub-menu collapsed&quot;]</value>
      <webElementGuid>9978d1bc-d074-4c75-98b2-88262c15e4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div/ul[4]/li</value>
      <webElementGuid>9a3897b6-3c1b-41fb-a268-7b30622cc91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KFC Points Transaction'])[1]/following::li[1]</value>
      <webElementGuid>f7797431-9e7c-47b4-a010-1edd118b2cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KFC Points Configuration'])[1]/following::li[2]</value>
      <webElementGuid>31d74f99-8872-44c4-a1d6-98f95d0ffe8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet Management'])[1]/preceding::li[1]</value>
      <webElementGuid>c815dde9-7528-4562-8b74-a2b9dc24e1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li</value>
      <webElementGuid>159e5f0f-987c-409c-b6df-fe7415eb69c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Master Data' or . = 'Master Data')]</value>
      <webElementGuid>99501a13-b464-4d3c-9202-64afccdde1dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
