<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Outlet Management</name>
   <tag></tag>
   <elementGuidId>d419c50b-93cb-4c94-8a44-a212a513f424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse5']/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse5 > ul.sub-side-menu > li.has-sub-menu.sub-menu.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cf96b122-323b-4675-bdf2-38584063aa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-sub-menu sub-menu collapsed</value>
      <webElementGuid>cafbfe44-62c1-4081-9976-38367eaabd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse5-1</value>
      <webElementGuid>c4120b67-29c9-4c23-ad89-4f85fe34d47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5a6e48c-f7bb-4990-9130-5ca3f0d5022c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20193df6-fd91-4fc4-847d-c4b695232226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outlet Management</value>
      <webElementGuid>756bdc40-5b62-419f-89d9-5b692cb877c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse5&quot;)/ul[@class=&quot;sub-side-menu&quot;]/li[@class=&quot;has-sub-menu sub-menu collapsed&quot;]</value>
      <webElementGuid>691fbd81-8cb6-4c5d-8b85-12e27d3c296d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse5']/ul/li</value>
      <webElementGuid>7c13a315-24fa-42d7-a950-ed046f74065b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::li[1]</value>
      <webElementGuid>8f19e4d9-8956-49e3-8fcf-fa1f972a5024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KFC Points Transaction'])[1]/following::li[2]</value>
      <webElementGuid>632a7944-5294-4a13-9a02-923793993e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet List'])[1]/preceding::li[1]</value>
      <webElementGuid>3cc93e25-67c8-44e6-a833-730a5fc3921e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/div/ul/li</value>
      <webElementGuid>08d2dab6-7922-4ac8-9e68-2664240dcc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Outlet Management' or . = 'Outlet Management')]</value>
      <webElementGuid>e0cb1052-af8f-47c7-b2ee-7adf4904c33d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
