<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dashboard___BVID__28__BV_toggle_</name>
   <tag></tag>
   <elementGuidId>eca3afe4-15ca-4a81-8d0d-6fd73f9cd7d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__BVID__28__BV_toggle_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__28__BV_toggle_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ad62b75-6acd-4c6d-aef1-e13771ac8370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f4cccc2-e3ae-4dfa-b4f3-2424802ca3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d43d46e-b034-4bc3-987e-a39045279a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1e2b792-e690-4d4e-ba93-522b25da9d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link dropdown-toggle</value>
      <webElementGuid>6bad99bb-c86e-4bc0-8c1e-cd6a2ae38b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__28__BV_toggle_</value>
      <webElementGuid>d722fe5b-5e16-46ce-9a81-7ec0f4a4eec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__28__BV_toggle_&quot;)</value>
      <webElementGuid>3aefe4e3-349b-4fca-bb4c-a0103333f734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__BVID__28__BV_toggle_']</value>
      <webElementGuid>3d0fe5c8-fbed-439f-8292-10a00592c705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__28']/button</value>
      <webElementGuid>1e961ab1-94b0-432e-b0e5-1811cbca2135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>96788386-a0f8-4214-ad2d-69e20cdfa903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '__BVID__28__BV_toggle_']</value>
      <webElementGuid>f480d128-6ece-4ac4-a596-2006c09f77a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
