<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dashboard___BVID__28__BV_toggle_</name>
   <tag></tag>
   <elementGuidId>7e24d3d4-95cd-4705-b9ac-92ffce55929c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__BVID__28__BV_toggle_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__28__BV_toggle_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04eb9fd6-b744-45ff-84e8-c44bc906e378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0bef3064-84f6-4820-b646-a52594f79fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dedcab80-6f17-4355-a104-b50f9f7fe7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5425bc46-9d36-486d-9380-c312e6a91818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link dropdown-toggle</value>
      <webElementGuid>4f227fd8-f6d4-487b-93a4-6bc3412c54c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__28__BV_toggle_</value>
      <webElementGuid>974f5cfb-64a8-471e-8e78-fc93d8d44e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__28__BV_toggle_&quot;)</value>
      <webElementGuid>0c134ef3-dd1e-4f85-a66e-86766deb86b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__BVID__28__BV_toggle_']</value>
      <webElementGuid>f504d4c6-73c4-43f5-a914-ee2f1c97c326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__28']/button</value>
      <webElementGuid>8ff3c25e-7ff5-4b9c-8038-8a9761cc0884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ea9af8e5-3a5a-41ff-a43e-fa66386fb827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '__BVID__28__BV_toggle_']</value>
      <webElementGuid>d7d2bd36-d791-4ed1-9cb9-ecd9ed0053ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
