<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Monthly_bar-chart</name>
   <tag></tag>
   <elementGuidId>1a1f2bbe-b480-45d4-980b-f933fe122bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='bar-chart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bar-chart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>3e4465b5-99ef-4595-be49-ba398bb3af79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bar-chart</value>
      <webElementGuid>accabc2f-233f-480d-9f25-1668a2d9e147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1533</value>
      <webElementGuid>2df2f6f6-b4e0-4850-a528-56fcc77644dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>a678b200-2bdc-4927-a5d5-ca2727322337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
      <webElementGuid>74c1ad10-6419-4c3a-8569-f9fb43cbc5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;main-menuboard&quot;]/div[2]/div[@class=&quot;row translate_0&quot;]/div[@class=&quot;canvas-container col-sm-12 col-12&quot;]/div[@class=&quot;dashboard-section&quot;]/div[2]/canvas[@id=&quot;bar-chart&quot;]</value>
      <webElementGuid>a7417b36-56f4-4403-8a73-4b6e44e2281d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='bar-chart']</value>
      <webElementGuid>4462ba03-1cc7-456b-b771-755737c47ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/canvas</value>
      <webElementGuid>87b8057c-0fd4-434f-82bc-99088322bfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>04c8d42c-daf0-4aa4-85f4-186657a00118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'bar-chart']</value>
      <webElementGuid>d2f67bf6-6a36-4674-8f60-f6925f0e0894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
